---
sidebar: sidebar 
permalink: deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: Nachdem Sie überprüft haben, ob das empfohlene FSX für ONTAP-Dateisystem oder Dateisysteme in einigen Fällen Ihren genauen Anforderungen entspricht, können Sie das System mithilfe der Workload-Fabrik in Ihrer AWS-Umgebung implementieren. 
---
= Stellen Sie das empfohlene FSX für ONTAP-Dateisystem bereit
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Nachdem Sie überprüft haben, ob das empfohlene Filesystem FSX für ONTAP (oder in einigen Fällen mehrere Filesysteme) Ihren genauen Anforderungen entspricht, können Sie das System mithilfe der Workload-Fabrik in Ihrer AWS-Umgebung implementieren.

Abhängig von den Richtlinien und Berechtigungen, die Sie Ihrem Workload Factory-Konto hinzugefügt haben, können Sie das FSx for ONTAP-Dateisystem vollständig mithilfe der Workload Factory (im Lese-/Schreibmodus) bereitstellen. Wenn Sie weniger Berechtigungen (Nur-Lese-Modus) oder keine Berechtigungen (Basismodus) haben, müssen Sie die CloudFormation-Vorlage aus der Codebox verwenden und das FSx für ONTAP-Dateisystem selbst in AWS bereitstellen.

.Anforderungen für Bereitstellungen im Amazon Elastic VMware Service
* Sie müssen über ein Abonnement für den Amazon Elastic VMware Service verfügen.
* Sie müssen über die erforderlichen Berechtigungen verfügen, um in Ihrem AWS-Konto ein FSx for ONTAP-Dateisystem zu erstellen.


.Schritte
. Wählen Sie unten auf der Seite *Prüfplan* *deploy* aus, und die Seite Erstellen eines FSX für ONTAP-Dateisystem wird angezeigt.
+
Die meisten Felder, die Ihr FSX für ONTAP-Dateisystem definieren, werden basierend auf den von Ihnen angegebenen Informationen ausgefüllt, aber es gibt ein paar Felder, die Sie auf dieser Seite ausfüllen müssen.

+
Sie können die Option schnell erstellen oder Erweitert erstellen verwenden. Advanced Create bietet einige zusätzliche Speicherparameter, die Sie anpassen können. https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Sehen Sie, was diese beiden Optionen bieten"]

. Geben Sie im Abschnitt „Allgemeine Konfiguration des Dateisystems“ die folgenden Informationen ein:
+
.. *AWS Zugangsdaten*: Wählen Sie oder fügen Sie Anmeldeinformationen hinzu, die Workload Factory die notwendigen Berechtigungen geben, um Ihr FSX for ONTAP Dateisystem direkt zu erstellen. Sie können auch den CloudFormation-Code aus der Codebox auswählen und das FSX für ONTAP-Dateisystem selbst in AWS bereitstellen.
.. *Dateisystemname*: Geben Sie den Namen ein, den Sie für dieses Dateisystem FSX for ONTAP verwenden möchten.
.. *Tags*: Optional können Sie Tags hinzufügen, um dieses FSx für ONTAP-Dateisystem zu kategorisieren.


. Geben Sie im Abschnitt „Netzwerk und Sicherheit“ die folgenden Informationen ein:
+
.. *Region und VPC*: Wählen Sie die Region und die VPC aus, in der das FSx for ONTAP-Dateisystem bereitgestellt wird.
.. *Sicherheitsgruppe* (Nur erweiterte Erstellung): Wenn Sie die Option *Erweiterte Erstellung* verwenden, können Sie die Standardsicherheitsgruppe für die FSx for ONTAP VPC auswählen, sodass der gesamte Datenverkehr auf das FSx for ONTAP-Dateisystem zugreifen kann. Sie können entweder eine neue Sicherheitsgruppe erstellen oder eine vorhandene auswählen.
+
Wenn Sie die Option *Sicherheitsgruppenkonfiguration an EVS NFS-Datenspeicher anpassen* aktivieren, konfiguriert Workload Factory die Sicherheitsgruppe entsprechend den Einstellungen für EVS NFS-Datenspeicher.

+
Sie können der Sicherheitsgruppe eine eingehende Regel hinzufügen, die den Zugriff anderer AWS-Dienste auf das FSx for ONTAP-Dateisystem einschränkt. Dadurch wird die Anzahl der geöffneten Dienste reduziert. Die Mindestports und Protokolle sind:

+
[cols="15,10,55"]
|===
| Protokolle | Ports | Zweck 


| TCP, UDP | 111 | Portmapper (zur Aushandlung der in NFS-Anfragen verwendeten Ports) 


| TCP, UDP | 635 | NFS-Mountd (erhält NFS-Mount-Anfragen) 


| TCP, UDP | 2049 | NFS-Netzwerkverkehr 


| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd) – verarbeitet Sperranforderungen. 


| TCP, UDP | 4046 | Network Status Monitor (NSM, statd) - benachrichtigt NFS-Clients über Neustarts des Servers für das Sperrmanagement. 
|===
.. *Verfügbarkeitszone*: Wählen Sie die Verfügbarkeitszone und das Subnetz aus.
+
Sie sollten dieselbe Verfügbarkeitszone auswählen, in der Ihr VMware SDDC implementiert ist, wenn Sie Kosten für AZ-übergreifenden Datenverkehr vermeiden möchten.

.. *Verschlüsselung* (nur Erweiterte Erstellung): Wenn Sie die Option *Erweiterte Erstellung* verwenden, können Sie den Namen des AWS-Verschlüsselungsschlüssels aus der Dropdown-Liste auswählen.
.. *Zugriff auf NFS-Datenspeicher* (nur erweiterte Erstellung): Wenn Sie die Option *Erweiterte Erstellung* verwenden, können Sie auswählen, ob alle Hosts auf die Datenspeicher zugreifen können oder ob nur der EVS-Verwaltungshost auf die Datenspeicher zugreifen kann.


. Geben Sie im Abschnitt „Dateisystemdetails“ die folgenden Informationen ein:
+
.. *ONTAP-Anmeldeinformationen*: Geben Sie das ONTAP-Benutzernamen-Passwort ein.
.. *Speicher-VM-Anmeldeinformationen* (nur Advanced create): Geben Sie das Passwort für die Speicher-VM ein und bestätigen Sie es. Das Kennwort kann spezifisch für dieses Dateisystem sein, oder Sie können dasselbe Kennwort verwenden, das für die ONTAP-Anmeldeinformationen eingegeben wurde.


. Im Abschnitt *Zusammenfassung* können Sie die FSX für ONTAP Dateisystem- und Datastore-Konfiguration anzeigen, die der VMware Migration Advisor basierend auf Ihren Informationen entwickelt hat.
. Wählen Sie *Erstellen*, um das FSX für ONTAP-Dateisystem bereitzustellen. Dieser Vorgang kann bis zu 2 Stunden dauern.
+
Optional können Sie im Codebox-Fenster *Zu CloudFormation umleiten* auswählen, um das Dateisystem und die empfohlene VM-Konfiguration mithilfe eines CloudFormation-Stacks zu erstellen.

+
In beiden Fällen können Sie den Erstellungsfortschritt in CloudFormation überwachen.



.Ergebnis
Das Dateisystem FSX für ONTAP wird bereitgestellt. Sie können jetzt die AWS CloudFormation-Vorlage in der Codebox verwenden, um die empfohlene VM-Konfiguration in Ihrer Amazon Elastic VMware Service-Umgebung bereitzustellen.
