---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works, migration, manual, specification, deploy, deployment, plan 
summary: Melden Sie sich bei der NetApp Workload Factory an, um auf das VMware-Planungscenter zuzugreifen.  Sie können einen Bereitstellungsplan für EVS manuell erstellen. 
---
= Manuelles Erstellen eines Bereitstellungsplans für Amazon EVS
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Melden Sie sich bei der NetApp Workload Factory an, um auf das VMware-Planungscenter zuzugreifen.  Von dort aus können Sie manuell einen Bereitstellungsplan oder Migrationsplan für Amazon EVS erstellen, der auf Ihre Anforderungen zugeschnitten ist.

Beachten Sie, dass Sie für den Zugriff auf Workload Factory einen Benutzernamen und ein Kennwort benötigen.  Wenn Sie keinen Zugriff haben, erstellen Sie jetzt ein Konto.  Siehe die Anweisungen https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["Hier"] .



== Erstellen Sie einen Bereitstellungsplan, indem Sie die Umgebungsanforderungen manuell angeben

Sie können Ihre Anforderungen für virtuelle Maschinen im Amazon Elastic VMware Service manuell angeben und angepasste Amazon FSx für NetApp ONTAP-Dateisysteme als externe Datenspeicher verwenden.

.Anforderungen
* Sie müssen über ein Abonnement für den Amazon Elastic VMware Service verfügen.


.Schritte
. Melden Sie sich bei Workload Factory mit einem der folgenden https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^] .
. Wenn Sie Workload Factory über die Workload Factory-Konsole aufgerufen haben, wählen Sie optional in der Kachel „VMware-Workloads“ *VMware Planning Center* und dann *VMware Planning Center* aus.  Das VMware-Planungscenter wird angezeigt.
. Wählen Sie *EVS-Plan manuell erstellen*.
. Geben Sie die Anforderungen für Ihre VM-Umgebung ein.
+
[NOTE]
====
Beachten Sie die folgenden Leistungsanforderungen und Empfehlungen für die VM-Migration:

** Aus Performancegründen wird für die VM-Inventarisierung eine Mindestspeicherkapazität von 10 TiB empfohlen.
** Für die Amazon Elastic VMware Service-Datenspeicher ist ein Mindestdurchsatz erforderlich, abhängig von der erforderlichen Anzahl an IOPS, die Sie für diese Bereitstellung angeben.
** Abhängig von der FSx for ONTAP-Dateisystemkonfiguration ist eine Mindestanzahl externer Datenspeicher erforderlich, damit die Amazon Elastic VMware Service-Umgebung eine optimale Leistung erreicht.


====
. Wenn Sie bereit sind, wählen Sie *Plan überprüfen* aus, um den Migrationsplan zu überprüfen.
. Überprüfen Sie den Plan. Erweitern Sie jeden Abschnitt, um die Plandetails anzuzeigen.
+
Standardmäßig speichert Workload Factory den Migrationsplan im Planungscenter.  Sie können diese Option oben auf der Seite deaktivieren.

. Wenn Sie mit dem Migrationsplan zufrieden sind, können Sie die Plandetails optional als PDF-Dokument herunterladen, indem Sie *Plan exportieren (PDF)* auswählen.
. Wenn Sie bereit sind, den Bereitstellungsplan bereitzustellen, wählen Sie *Bereitstellen*.


link:deploy-fsx-file-system-evs.html["Implementieren Sie das von VMware-Workloads empfohlene FSX für ONTAP-Filesystem"].
