---
sidebar: sidebar 
permalink: learn-about-vmware-workloads.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works 
summary: 'NetApp Workload Factory für VMware bietet Tools zum Verschieben Ihrer Daten von lokalen Systemen zu Amazon EVS, VMware Cloud on AWS (VMC) oder Amazon EC2.' 
---
= Erfahren Sie mehr über NetApp Workload Factory für VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory für VMware bietet Tools zum Verschieben Ihrer Daten von lokalen Systemen zu Amazon Elastic VMware Service (EVS), VMware Cloud on AWS (VMC) oder Amazon EC2.



== Was ist NetApp Workload Factory für VMware?

NetApp Workload Factory für VMware bietet ein Planungscenter und Migrationsberater, mit denen Sie Ihre aktuellen Konfigurationen virtueller Maschinen in lokalen vSphere-Umgebungen analysieren können.  Die Migrationsberater erstellen dann einen Plan zur Bereitstellung empfohlener VM-Layouts auf Amazon EVS-, Amazon EC2- oder VMware Cloud auf AWS vSphere-Clustern und verwenden angepasste Amazon FSx for NetApp ONTAP -Dateisysteme als externe Datenspeicher.  Das Planungscenter fungiert als Dashboard der Workload Factory für VMware und ermöglicht Ihnen die Verwaltung gespeicherter VM-Inventardatensätze und gespeicherter Migrationspläne sowie die Bereitstellung aller von Ihnen gespeicherten Migrationspläne.

Amazon FSx for NetApp ONTAP ist ein externer NFS-Datenspeicher, der auf dem ONTAP Dateisystem von NetApp basiert und an Amazon EVS- oder Amazon EC2-Instanzen oder VMware Cloud auf AWS vSphere-Clustern angeschlossen werden kann.  Es ist nicht erforderlich, weitere Hosts hinzuzufügen, um den verfügbaren Speicher zu erhöhen. Verwenden Sie stattdessen einfach FSx für ONTAP -Volumes als externe Datenspeicher, um vSAN-Datenspeicher zu ergänzen.  Dadurch erhalten Sie eine flexible, leistungsstarke, virtualisierte Speicherinfrastruktur, die unabhängig von den Rechenressourcen skaliert.

Weitere Informationen zu Workload Factory finden Sie im https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Übersicht über Workload Factory"^] .



== So funktionieren die VMware-Migrationsberater

Die Migrationsberater können Ihnen dabei helfen, lokale virtuelle Maschinen (VMs) und deren Daten, die auf allen von VMware unterstützten Datenspeichern ausgeführt werden, in Amazon EVS-, Amazon EC2- oder VMware Cloud-Datenspeicher zu verschieben, was zusätzliche NFS-Datenspeicher auf einem FSx für ONTAP Dateisystem umfasst.

Beachten Sie, dass Sie bis zu vier (4) FSX für ONTAP-Volumes an ein einzelnes vSphere-Cluster in VMware Cloud on AWS anschließen können.



== Was Sie mit den Migrationsberatern tun können

Die Migrationsberater bieten die folgenden Funktionen:

* Analyse aktueller VM-Konfigurationen vor Ort
* Bestimmen Sie, welche VMs zu Amazon EC2, Amazon EVS oder VMware Cloud auf AWS migriert werden sollen
* Ermitteln Sie den Speicherplatz, der auf FSX für ONTAP-Volumes zur Nutzung als externe VM-Datastores erforderlich ist
* Überprüfen Sie den Ergebnisbericht, um die Implementierungsschritte zu verstehen
* Durchführung der eigentlichen Implementierung


Der Migrationsberater unterstützt die Konfigurationsplanung für eine einzelne Amazon EVS- oder Amazon EC2-Instanz oder einen VMware Cloud on AWS-Cluster, der mit einem einzelnen FSx for ONTAP Dateisystem verbunden ist.



== Vorteile der Nutzung der Migrationsberater

Die Transition von Teilen Ihrer aktuellen Infrastruktur zu Amazon EC2 oder VMware Cloud on AWS mit Amazon FSX for ONTAP als externe NFS-Datastores bietet folgende Vorteile:

* Kostenoptimierung durch Entkopplung von Host und Storage und erweiterte Dateneffizienz
* Bedarfsunabhängige Erweiterung der Storage-Kapazität, ohne dass zusätzliche Host-Instanzen angeschafft werden müssen
* NetApp ONTAP Datenmanagementfunktionen in der Cloud wie z. B. platzsparende Snapshots, Klonen, Komprimierung, Deduplizierung, Data-Compaction und Replizierung
* Weniger Management von Hardware-Aktualisierungen
* Möglichkeit zum Ändern des Datendurchsatzes, der IOPS-Werte und der Größe des Filesystems sowie zum Erhöhen oder verringern der Volume-Größe
* Hochverfügbarkeit bei Unterstützung mehrerer Verfügbarkeitszonen-Implementierungen (Availability Zone, AZ)
* Kosten- und Latenzreduzierung für einzelne-AZ-Konfigurationen, die VPC-Peering ohne Transit-Gateway verwenden




== Tools zur Verwendung von NetApp Workload Factory

Sie können NetApp Workload Factory mit den folgenden Tools verwenden:

* *Workload Factory-Konsole*: Die Workload Factory-Konsole bietet eine visuelle, ganzheitliche Ansicht Ihrer Anwendungen und Projekte.
* * NetApp Konsole*: Die NetApp Konsole bietet eine hybride Benutzeroberfläche, sodass Sie Workload Factory zusammen mit anderen NetApp -Datendiensten verwenden können.
* *Fragen Sie mich*: Verwenden Sie den KI-Assistenten „Fragen Sie mich“, um Fragen zu stellen und mehr über Workload Factory zu erfahren, ohne die Workload Factory-Konsole zu verlassen. Greifen Sie über das Hilfemenü von Workload Factory auf „Fragen Sie mich“ zu.
* *CloudShell CLI*: Workload Factory enthält eine CloudShell CLI zum Verwalten und Betreiben von AWS- und NetApp -Umgebungen über Konten hinweg von einer einzigen, browserbasierten CLI aus. Greifen Sie über die obere Leiste der Workload Factory-Konsole auf CloudShell zu.
* *REST-API*: Verwenden Sie die Workload Factory REST-APIs, um Ihre FSx für ONTAP Dateisysteme und andere AWS-Ressourcen bereitzustellen und zu verwalten.
* *CloudFormation*: Verwenden Sie AWS CloudFormation-Code, um die Aktionen auszuführen, die Sie in der Workload Factory-Konsole definiert haben, um AWS- und Drittanbieterressourcen aus dem CloudFormation-Stack in Ihrem AWS-Konto zu modellieren, bereitzustellen und zu verwalten.
* *Terraform NetApp Workload Factory-Anbieter*: Verwenden Sie Terraform, um in der Workload Factory-Konsole generierte Infrastruktur-Workflows zu erstellen und zu verwalten.




== Kosten

Die Nutzung von Workload Factory für VMware ist kostenlos.

Sie müssen für AWS-Ressourcen bezahlen, die Sie basierend auf den Empfehlungen der Migrationsberater bereitstellen.



== Lizenzierung

Für die Verwendung von Workload Factory für VMware sind keine speziellen Lizenzen von NetApp erforderlich.



== Regionen

Workload Factory wird in allen kommerziellen Regionen unterstützt, in denen FSx für ONTAP unterstützt wird. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Sehen Sie sich die unterstützten Amazon-Regionen an."^]

Die folgenden AWS-Regionen werden nicht unterstützt:

* Regionen Chinas
* GovCloud (USA)-Regionen
* Geheime Cloud
* Streng geheime Cloud

