---
sidebar: sidebar 
permalink: migrate-data-native.html 
keywords: vm workloads, fsx for ontap, migration, data migration, vmware hcx 
summary: 'Verwenden Sie ein Tool wie AWS Application Migration Service (MGN), um Ihre Daten aus Ihrem alten Virtual Machine Storage in die FSX for NetApp ONTAP Volumes zu verschieben, die mit Ihren neuen Virtual Machines verbunden sind.' 
---
= Migrieren Sie Ihre Daten zur neuen Infrastruktur
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Verwenden Sie ein Tool wie AWS Application Migration Service (MGN), um Ihre Daten aus Ihrem alten Virtual Machine Storage in die FSX for NetApp ONTAP Volumes zu verschieben, die mit Ihren neuen Virtual Machines verbunden sind.

AWS MGN ermöglicht Ihnen die Migration Ihrer Applikationen zu FSX for NetApp ONTAP Volumes in Amazon EC2.

https://docs.aws.amazon.com/mgn/latest/ug/what-is-application-migration-service.html["Lesen Sie die Dokumentation zum AWS Application Migration Service"^] Genaue Informationen.

.Was kommt als Nächstes?
Nachdem Sie nun Ihre Daten zu externen Datastores in AWS und Amazon FSX for NetApp ONTAP migriert haben, können Sie die wichtigen Daten in Ihrem FSX für ONTAP Filesystem sichern und schützen, damit Ihre Daten immer verfügbar sind.

Informationen zum Verwalten Ihres FSX für ONTAP-Dateisystems finden Sie unter, um die https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Dokumentation zu Amazon FSX für NetApp ONTAP"] Backup- und Schutzfunktionen anzuzeigen, die Sie verwenden können.
