---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Informieren Sie sich über die Neuerungen bei der Komponente VMware Migration Advisor von Workload Factory. 
---
= Was ist neu
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die Neuerungen bei der Komponente VMware Cloud Migration Advisor von Workload Factory.



== 19 September 2024



=== Verbesserungen bei VMware Migration Advisor

Diese Version von Workload Factory für VMware bietet Verbesserungen an Funktionalität und Stabilität sowie die Möglichkeit, Migrationspläne mithilfe des VMware Migrationsberaters zu importieren und zu exportieren.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Erstellen eines Implementierungsplans für Amazon EC2 mithilfe des Migrationsberaters"]



== 1 September 2024



=== Migrieren Sie zu Amazon EC2

Workload Factory für VMware unterstützt jetzt die Migration zu Amazon EC2 mithilfe des VMware Migrationsberaters.



== 7 Juli 2024



=== Erstversion von Workload Factory für VMware

Die erste Version umfasst die Möglichkeit, mithilfe des VMware Migrationsberaters Ihre aktuellen Konfigurationen von Virtual Machines in lokalen vSphere Umgebungen zu analysieren, einen Plan für die Implementierung empfohlener VM-Layouts in VMware Cloud on AWS zu erstellen und die benutzerdefinierten Amazon FSX for NetApp ONTAP Filesysteme als externe Datastores zu verwenden.
