= Einführung der Unterstützung für migration advisor für Google Cloud VMware Engine
:allow-uri-read: 




=== Einführung der Unterstützung für migration advisor für Google Cloud VMware Engine

NetApp Workload Factory unterstützt jetzt Google Cloud VMware Engine. Sie können Ihre lokalen VMware-Workloads zu Google Cloud VMware Engine migrieren, indem Sie Google Cloud NetApp Volumes als externe NFS-Datenspeicher verwenden. So optimieren Sie die Kosten und erhalten mehr Kontrolle über Ihre VMware-Umgebung, ohne Ihre Anwendungen refaktorisieren oder auf eine neue Plattform umstellen zu müssen.

Der Google Cloud VMware Engine Migrationsberater bietet:

* Automatisierte Dimensionierung und Auslegung von Google Cloud VMware Engine-Cluster mit Unterstützung für VE1- und VE2-Knotentypen
* VM-Layoutoptimierung zwischen internen vSAN-Datenspeichern und externen NFS-Datenspeichern von Google Cloud NetApp Volumes.
* Detaillierter Kostenvergleich und TCO-Analyse zwischen reinen vSAN- und Google Cloud NetApp Volumes-basierten Konfigurationen.
* Unterstützung für die Servicelevel Standard, Premium und Extreme von Google Cloud NetApp Volumes.
* Infrastructure-as-Code-Bereitstellung mit Terraform für die automatisierte Bereitstellung.

